[library]
title = "Built-in Cognite packages"

[packages.quickstart]
title = "Quickstart"
description = "Get started with Cognite Data Fusion in minutes."
canCherryPick = false
modules = [
    "modules/cdf_ingestion",
    "modules/sourcesystem/cdf_pi",
    "modules/sourcesystem/cdf_sap_assets",
    "modules/sourcesystem/cdf_sap_events",
    "modules/sourcesystem/cdf_sharepoint",
    "modules/models/cdf_process_industry_extension",
    "modules/contextualization/cdf_connection_sql",
    "modules/contextualization/cdf_p_and_id_parser",
    "modules/industrial_tools/cdf_search"
]

[packages.infield]
title = "InField"
description = "Put real-time data into the hands of every field worker."
modules = [
    "modules/infield/cdf_infield_location",
    "modules/infield/cdf_infield_second_location",
    "modules/infield/cdf_infield_common",
    "modules/common/cdf_apm_base"
]

[packages.inrobot]
title = "InRobot"
description = "Capture and integrate a broad spectrum of robotics inspection data with other IT and OT data through AI-assisted, optimized data management."
modules = [
    "modules/inrobot/cdf_inrobot_location",
    "modules/inrobot/cdf_inrobot_common",
    "modules/common/cdf_apm_base"
]

[packages.industrial_tools]
title = "Industrial Tools"
description = "Data exploration and analytics"
modules = [
    "modules/industrial_tools/cdf_location_filter_datamodel_based",
    "modules/industrial_tools/cdf_search",
    "modules/industrial_tools/cdf_location_filter_asset_centric"
]

[packages.bootcamp]
title = "Bootcamp"
description = "Initial toolkit configurations for the Cognite Data Fusion Bootcamp"
canCherryPick = false
modules = [
    "modules/bootcamp/ice_cream_api",
    "modules/bootcamp/use_cases/oee"
]

[packages.sourcesystem]
title = "SourceSystem"
description = "Module templates for setting up a data pipeline from a source system"
modules = [
    "modules/sourcesystem/cdf_pi",
    "modules/sourcesystem/cdf_sap_assets",
    "modules/sourcesystem/cdf_sap_events",
    "modules/sourcesystem/cdf_sharepoint"
]

[packages.contextualization]
title = "Contextualization"
description = "Module templates for data contextualization"
modules = [
    "modules/contextualization/cdf_p_and_id_parser",
    "modules/contextualization/cdf_connection_sql",
    "modules/contextualization/cdf_entity_matching"
]

[packages.models]
title = "Models"
description = "Module templates for data models"
modules = [
    "modules/models/cdf_cdm_extension",
    "modules/models/cdf_process_industry_extension",
    "modules/models/cdf_cdm_extension_full",
    "modules/models/cdf_scene",
    "modules/models/cdf_process_industry_extension_full"
]

[packages.custom]
title = "None"
description = "start with an empty module"
modules = [
    "modules/custom/my_module",
    "modules/common/cdf_auth_readwrite_all"
]

[packages.common]
title = "Common"
description = "Common modules used by other packages"
modules = [
    "modules/cdf_common",
    "modules/common/cdf_apm_base",
    "modules/common/cdf_auth_readwrite_all"
] 
