[library]
title = "Built-in Cognite packages"
description = "Built-in Cognite packages"

[packages.quickstart]
title = "Quickstart"
id = "tk:quickstart"
description = "Get started with Cognite Data Fusion in minutes."
canCherryPick = false
modules = [
    "cdf_ingestion",
    "sourcesystem/cdf_pi",
    "sourcesystem/cdf_sap_assets",
    "sourcesystem/cdf_sap_events",
    "sourcesystem/cdf_sharepoint",
    "models/cdf_process_industry_extension",
    "contextualization/cdf_connection_sql",
    "contextualization/cdf_p_and_id_parser",
    "industrial_tools/cdf_search"
]

[packages.infield]
title = "InField"
id = "tk:infield"
description = "Put real-time data into the hands of every field worker."
modules = [
    "infield/cdf_infield_location",
    "infield/cdf_infield_second_location",
    "infield/cdf_infield_common",
    "common/cdf_apm_base"
]

[packages.infield_quickstart]
title = "InField Quickstart"
id = "tk:infield_quickstart"
description = "Put real-time data into the hands of every field worker."
modules = [
    "infield_quickstart/cdf_infield_common",
    "infield_quickstart/cdf_infield_location",
]

[packages.infield_on_cdm]
title = "InField on CDM"
id = "tk:infield_on_cdm"
description = "Put real-time data into the hands of every field worker."
modules = [
    "cdf_infield_on_cdm_common",
    "cdf_infield_on_cdm_location",
    "cdf_infield_on_cdm_location_example_data",
]

[packages.infield_on_cdm_extention]
title = "InField on CDM extention"
id = "tk:infield_on_cdm_extention"
description = "Put real-time data into the hands of every field worker."
modules = [
    "cdf_infield_on_cdm_common",
    "cdf_infield_on_cdm_common_extention",
    "cdf_infield_on_cdm_location_extention",
    "cdf_infield_on_cdm_location_example_data_extention",
]

[packages.inrobot]
title = "InRobot"
id = "tk:inrobot"
description = "Capture and integrate a broad spectrum of robotics inspection data with other IT and OT data through AI-assisted, optimized data management."
modules = [
    "inrobot/cdf_inrobot_location",
    "inrobot/cdf_inrobot_common",
    "common/cdf_apm_base"
]

[packages.industrial_tools]
title = "Industrial Tools"
id = "tk:industrial_tools"
description = "Data exploration and analytics"
modules = [
    "industrial_tools/cdf_location_filter_datamodel_based",
    "industrial_tools/cdf_search",
    "industrial_tools/cdf_location_filter_asset_centric"
]

[packages.bootcamp]
title = "Bootcamp"
id = "tk:bootcamp"
description = "Initial toolkit configurations for the Cognite Data Fusion Bootcamp"
canCherryPick = false
modules = [
    "bootcamp/ice_cream_api",
    "bootcamp/use_cases/oee"
]

[packages.sourcesystem]
title = "SourceSystem"
id = "tk:sourcesystem"
description = "Module templates for setting up a data pipeline from a source system"
modules = [
    "sourcesystem/cdf_pi",
    "sourcesystem/cdf_sap_assets",
    "sourcesystem/cdf_sap_events",
    "sourcesystem/cdf_sharepoint"
]

[packages.contextualization]
title = "Contextualization"
id = "tk:contextualization"
description = "Module templates for data contextualization"
modules = [
    "contextualization/cdf_p_and_id_parser",
    "contextualization/cdf_connection_sql",
    "contextualization/cdf_entity_matching"
]

[packages.models]
title = "Models"
id = "tk:models"
description = "Module templates for data models"
modules = [
    "models/cdf_cdm_extension",
    "models/cdf_process_industry_extension",
    "models/cdf_cdm_extension_full",
    "models/cdf_scene",
    "models/cdf_process_industry_extension_full"
]

[packages.custom]
title = "None"
id = "tk:custom"
description = "start with an empty module"
modules = [
    "custom/my_module",
    "common/cdf_auth_readwrite_all"
]

[packages.common]
title = "Common"
id = "tk:common"
description = "Common modules used by other packages"
modules = [
    "cdf_common",
    "common/cdf_apm_base",
    "common/cdf_auth_readwrite_all"
] 
