[packages]
title = "Built-in Cognite packages"

# QUICKSTART ============================================================
[packages.quickstart]
title = "Quickstart"
description = "Get started with Cognite Data Fusion in minutes."
canCherryPick = false

[[packages.quickstart.modules]]
title = "Ingestion Workflow"
path = "cdf_ingestion"
is_selected_by_default = true
dependencies = { modules = [] }
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" }
]

[[packages.quickstart.modules]]
title = "OSIsoft/AVEVA PI Data Source"
path = "sourcesystem/cdf_pi"
is_selected_by_default = false
dependencies = { modules = [] }
data = [
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit", source = "publicdata/pi_timeseries.Table.csv", destination = "raw/timeseries.Table.csv" }
]
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/raw/source.DataBase.yaml" },
    { location = "models/cdf_process_industry_extension/data_models" }
]

[[packages.quickstart.modules]]
title = "SAP Source System Asset/Equipment Metadata"
path = "sourcesystem/cdf_sap_assets"
dependencies = { modules = [] }
data = [
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit", source = "publicdata/assets.Table.csv", destination = "raw/dump.Table.csv" }
]
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/raw/source.DataBase.yaml" },
    { location = "models/cdf_process_industry_extension/data_models" }
]

[[packages.quickstart.modules]]
title = "SAP Source System Events"
path = "sourcesystem/cdf_sap_events"
data = [
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit/publicdata", source = "workitem.Table.csv;workorder.Table.csv;workpackage.Table.csv;worktask.Table.csv", destination = "raw/" }
]
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/raw/source.DataBase.yaml" },
    { location = "models/cdf_process_industry_extension/data_models" }
]

[[packages.quickstart.modules]]
title = "Sharepoint Files"
path = "sourcesystem/cdf_sharepoint"
data = [
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit/publicdata/files", source = "PH-25578-P-4110006-001.pdf;PH-25578-P-4110010-001.pdf;PH-25578-P-4110119-001.pdf;PH-ME-P-0003-001.pdf;PH-ME-P-0004-001.pdf;PH-ME-P-0151-001.pdf;PH-ME-P-0152-001.pdf;PH-ME-P-0153-001.pdf;PH-ME-P-0156-001.pdf;PH-ME-P-0156-002.pdf;PH-ME-P-0160-001.pdf", destination = "files/" },
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit", source = "publicdata/valhall_file_metadata.csv", destination = "raw/files.Table.csv" }
]
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/raw/source.DataBase.yaml" },
    { location = "models/cdf_process_industry_extension/data_models" }
]

[[packages.quickstart.modules]]
title = "Example of Minimum Extension of the Cognite Process Industry Model"
path = "models/cdf_process_industry_extension"

[[packages.quickstart.modules]]
title = "Contextualisation direct relation transformation"
path = "contextualization/cdf_connection_sql"
is_selected_by_default = false
dependencies = { modules = [] }
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" }
]

[[packages.quickstart.modules]]
title = "Contextualization P&ID Diagram Parser"
path = "contextualization/cdf_p_and_id_parser"
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/extraction_pipelines/ctx_files_direct_relation_write.config.yaml" },
    { location = "cdf_common/extraction_pipelines/ctx_files_direct_relation_write.ExtractionPipeline.yaml" },
    { location = "cdf_common/functions/contextualization_connection_writer" },
    { location = "cdf_common/functions/write.Function.yaml" },
    { location = "cdf_common/raw/contextualization_state.DataBase.yaml" }
]

[[packages.quickstart.modules]]
title = "Search configuration with location filter"
path = "industrial_tools/cdf_search"
extra_resources = [
    { location = "cdf_common/data_models/demo.Space.yaml" }
]

# INFIELD ================================================================
[packages.infield]
title = "InField"
description = "Put real-time data into the hands of every field worker."

[[packages.infield.modules]]
title = "InField Location"
path = "infield/cdf_infield_location"
is_selected_by_default = true

[[packages.infield.modules]]
title = "InField Second Location"
path = "infield/cdf_infield_second_location"
is_selected_by_default = false

[[packages.infield.modules]]
title = "InField Common"
path = "infield/cdf_infield_common"
is_selected_by_default = true
dependencies = { modules = ["cdf_apm_base"] }

[[packages.infield.modules]]
title = "APM Base"
path = "common/cdf_apm_base"
is_selected_by_default = false

# INROBOT ================================================================
[packages.inrobot]
title = "InRobot"
description = "Capture and integrate a broad spectrum of robotics inspection data with other IT and OT data through AI-assisted, optimized data management."

[[packages.inrobot.modules]]
title = "InRobot Location"
path = "inrobot/cdf_inrobot_location"
is_selected_by_default = true

[[packages.inrobot.modules]]
title = "InRobot Common"
path = "inrobot/cdf_inrobot_common"
is_selected_by_default = true
dependencies = { modules = ["cdf_apm_base"] }

[[packages.inrobot.modules]]
title = "APM Base"
path = "common/cdf_apm_base"
is_selected_by_default = false

# INDUSTRIAL_TOOLS =====================================================
[packages.industrial_tools]
title = "Industrial Tools"
description = "Data exploration and analytics"

[[packages.industrial_tools.modules]]
title = "Example location filter datamodel based"
path = "industrial_tools/cdf_location_filter_datamodel_based"

[[packages.industrial_tools.modules]]
title = "Search configuration with location filter"
path = "industrial_tools/cdf_search"
extra_resources = [
    { location = "cdf_common/data_models/demo.Space.yaml" }
]

[[packages.industrial_tools.modules]]
title = "Example location filter asset centric"
path = "industrial_tools/cdf_location_filter_asset_centric"

# BOOTCAMP ===============================================================
[packages.bootcamp]
title = "Bootcamp"
description = "Initial toolkit configurations for the Cognite Data Fusion Bootcamp"
canCherryPick = false

[[packages.bootcamp.modules]]
title = "Bootcamp"
path = "bootcamp"
is_selected_by_default = false

[[packages.bootcamp.modules]]
title = "Bootcamp"
path = "bootcamp/ice_cream_api"
is_selected_by_default = true

[[packages.bootcamp.modules]]
title = "Bootcamp"
path = "bootcamp/use_cases/oee"
is_selected_by_default = true

# SOURCESYSTEM ===========================================================
[packages.sourcesystem]
title = "SourceSystem"
description = "Module templates for setting up a data pipeline from a source system"

[[packages.sourcesystem.modules]]
title = "OSIsoft/AVEVA PI Data Source"
path = "sourcesystem/cdf_pi"
is_selected_by_default = false
dependencies = { modules = [] }
data = [
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit", source = "publicdata/pi_timeseries.Table.csv", destination = "raw/timeseries.Table.csv" }
]
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/raw/source.DataBase.yaml" },
    { location = "models/cdf_process_industry_extension/data_models" }
]

[[packages.sourcesystem.modules]]
title = "SAP Source System Asset/Equipment Metadata"
path = "sourcesystem/cdf_sap_assets"
dependencies = { modules = [] }
data = [
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit", source = "publicdata/assets.Table.csv", destination = "raw/dump.Table.csv" }
]
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/raw/source.DataBase.yaml" },
    { location = "models/cdf_process_industry_extension/data_models" }
]

[[packages.sourcesystem.modules]]
title = "SAP Source System Events"
path = "sourcesystem/cdf_sap_events"
data = [
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit/publicdata", source = "workitem.Table.csv;workorder.Table.csv;workpackage.Table.csv;worktask.Table.csv", destination = "raw/" }
]
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/raw/source.DataBase.yaml" },
    { location = "models/cdf_process_industry_extension/data_models" }
]

[[packages.sourcesystem.modules]]
title = "Sharepoint Files"
path = "sourcesystem/cdf_sharepoint"
data = [
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit/publicdata/files", source = "PH-25578-P-4110006-001.pdf;PH-25578-P-4110010-001.pdf;PH-25578-P-4110119-001.pdf;PH-ME-P-0003-001.pdf;PH-ME-P-0004-001.pdf;PH-ME-P-0151-001.pdf;PH-ME-P-0152-001.pdf;PH-ME-P-0153-001.pdf;PH-ME-P-0156-001.pdf;PH-ME-P-0156-002.pdf;PH-ME-P-0160-001.pdf", destination = "files/" },
    { repoType = "http", repo = "https://apps-cdn.cogniteapp.com/toolkit", source = "publicdata/valhall_file_metadata.csv", destination = "raw/files.Table.csv" }
]
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/raw/source.DataBase.yaml" },
    { location = "models/cdf_process_industry_extension/data_models" }
]

# CONTEXTUALIZATION ======================================================
[packages.contextualization]
title = "Contextualization"
description = "Module templates for data contextualization"

[[packages.contextualization.modules]]
title = "Contextualization P&ID Diagram Parser"
path = "contextualization/cdf_p_and_id_parser"
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/extraction_pipelines/ctx_files_direct_relation_write.config.yaml" },
    { location = "cdf_common/extraction_pipelines/ctx_files_direct_relation_write.ExtractionPipeline.yaml" },
    { location = "cdf_common/functions/contextualization_connection_writer" },
    { location = "cdf_common/functions/write.Function.yaml" },
    { location = "cdf_common/raw/contextualization_state.DataBase.yaml" }
]

[[packages.contextualization.modules]]
title = "Contextualisation direct relation transformation"
path = "contextualization/cdf_connection_sql"
is_selected_by_default = false
dependencies = { modules = [] }
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" }
]

[[packages.contextualization.modules]]
title = "Contextualization Entity Matching"
path = "contextualization/cdf_entity_matching"
extra_resources = [
    { location = "cdf_common/data_sets/demo.DataSet.yaml" },
    { location = "cdf_common/data_models/demo.Space.yaml" },
    { location = "cdf_common/extraction_pipelines/ctx_files_direct_relation_write.config.yaml" },
    { location = "cdf_common/extraction_pipelines/ctx_files_direct_relation_write.ExtractionPipeline.yaml" },
    { location = "cdf_common/functions/contextualization_connection_writer" },
    { location = "cdf_common/functions/write.Function.yaml" },
    { location = "cdf_common/raw/contextualization_state.DataBase.yaml" }
]

# MODELS =================================================================
[packages.models]
title = "Models"
description = "Module templates for data models"

[[packages.models.modules]]
title = "Example of Minimum Extension of the Cognite Core Model"
path = "models/cdf_cdm_extension"

[[packages.models.modules]]
title = "Example of Minimum Extension of the Cognite Process Industry Model"
path = "models/cdf_process_industry_extension"

[[packages.models.modules]]
title = "Example of CogniteCore Extension Model"
path = "models/cdf_cdm_extension_full"

[[packages.models.modules]]
title = "(Alpha) Scene Data Model"
path = "models/cdf_scene"

[[packages.models.modules]]
title = "Example of CogniteProcessIndustry Extension Model"
path = "models/cdf_process_industry_extension_full"

# CUSTOM =================================================================
[packages.custom]
title = "None"
description = "start with an empty module"

[[packages.custom.modules]]
title = "Empty module"
path = "custom/my_module"

[[packages.custom.modules]]
title = "Admin group for CI/CD"
path = "common/cdf_auth_readwrite_all"

# COMMON =================================================================
[packages.common]
title = "Common"
description = "Common modules used by other packages"

[[packages.common.modules]]
title = "cdf_common"
path = "cdf_common"
is_selected_by_default = false

[[packages.common.modules]]
title = "APM Base"
path = "common/cdf_apm_base"
is_selected_by_default = false

[[packages.common.modules]]
title = "Admin group for CI/CD"
path = "common/cdf_auth_readwrite_all"
