space: infield_cdm_source_desc_sche_asset_file_ts
externalId: InFieldCDMLocationConfig
version: v1
name: InFieldCDMLocationConfig
implements: []
filter:
  hasData:
    - type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
properties:
  name:
    name: name
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: name
    description: Name of the location configuration
  description:
    name: description
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: description
    description: Description of the location configuration
  featureToggles:
    name: featureToggles
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: featureToggles
    description: Feature toggles for the location
  dataFilters:
    name: dataFilters
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: dataFilters
    description: Data filters for the location
  dataStorage:
    name: dataStorage
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: dataStorage
    description: Data storage configuration for the location
  viewMappings:
    name: viewMappings
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: viewMappings
    description: View mappings for the location
  accessManagement:
    name: accessManagement
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: accessManagement
    description: Access management configuration for the location
  disciplines:
    name: discipline
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: disciplines
    description: Discipline configuration for the location
  dataExplorationConfig:
    name: dataExplorationConfig
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: InFieldCDMLocationConfig
    containerPropertyIdentifier: dataExplorationConfig
    description: Data exploration configuration for the location

