space: infield_cdm_source_desc_sche_asset_file_ts
externalId: ObservationConfig
version: v1
name: ObservationConfig
implements: []
filter:
  hasData:
    - type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: ObservationConfig
properties:
  rootLocationExternalIds:
    name: rootLocationExternalIds
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: ObservationConfig
    containerPropertyIdentifier: rootLocationExternalIds
    description: List of externalIds for the locations this observation config is relevant for
  fieldConfigurations:
    name: fieldConfigurations
    container:
      type: container
      space: infield_cdm_source_desc_sche_asset_file_ts
      externalId: ObservationConfig
    containerPropertyIdentifier: fieldConfigurations
    description: For each field in observation, you can configure display name, description and value options for preset dropdown selections

