space: infield_cdm_source_desc_sche_asset_file_ts
externalId: InFieldLocationConfig
usedFor: node
properties:
  rootLocationExternalId:
    nullable: true
    type:
      list: false
      collation: ucs_basic
      type: text
  featureToggles:
    nullable: true
    type:
      list: false
      type: json
  classicAssetExternalId:
    nullable: true
    type:
      list: false
      collation: ucs_basic
      type: text
  rootAsset:
    nullable: true
    type:
      type: direct
      container:
        type: container
        space: cdf_cdm
        externalId: CogniteAsset
      list: false
  appInstanceSpace:
    nullable: true
    type:
      list: false
      collation: ucs_basic
      type: text
  appDataSet:
    nullable: true
    type:
      list: false
      collation: ucs_basic
      type: text
  dataFilters:
    nullable: true
    type:
      list: false
      type: json
  accessManagement:
    nullable: true
    type:
      list: false
      type: json
  disciplines:
    nullable: true
    type:
      list: true
      type: json
  observationConfig:
    nullable: true
    type:
      type: direct
      container:
        type: container
        space: infield_cdm_source_desc_sche_asset_file_ts
        externalId: ObservationConfig
      list: false
  dataExplorationConfig:
    nullable: true
    type:
      type: direct
      container:
        type: container
        space: infield_cdm_source_desc_sche_asset_file_ts
        externalId: DataExplorationConfig
      list: false

