space: infield_cdm_source_desc_sche_asset_file_ts
externalId: InFieldCDMLocationConfig
usedFor: node
properties:
  name:
    nullable: true
    type:
      list: false
      collation: ucs_basic
      type: text
  description:
    nullable: true
    type:
      list: false
      collation: ucs_basic
      type: text
  featureToggles:
    nullable: true
    type:
      list: false
      type: json
  dataFilters:
    nullable: true
    type:
      list: false
      type: json
  dataStorage:
    nullable: true
    type:
      list: false
      type: json
  viewMappings:
    nullable: true
    type:
      list: false
      type: json
  accessManagement:
    nullable: true
    type:
      list: false
      type: json
  disciplines:
    nullable: true
    type:
      list: true
      type: json
  dataExplorationConfig:
    nullable: true
    type:
      list: false
      type: json

