space: infield_cdm_source_desc_sche_asset_file_ts
externalId: ObservationConfig
usedFor: node
properties:
  rootLocationExternalIds:
    nullable: true
    type:
      list: true
      collation: ucs_basic
      type: text
  fieldConfigurations:
    nullable: true
    type:
      list: false
      type: json

