[module]
title = "cdf_infield_on_cdm_location_example_data_extention"
is_selected_by_default = false
id = "cdf_infield_on_cdm_location_example_data_extention"
package_id = "tk:infield_on_cdm_extention"

