location: <change_me>
location_name: <change_me>
location_description: <change_me>

# subtree filtering
subtree_asset_externalId: <change_me>

# groups
infield_location_normal_users_source_id: <change_me>
infield_location_template_admin_users_source_id: <change_me>
infield_location_checklist_admin_users_source_id: <change_me>
infield_location_viewer_users_source_id: <change_me>
